workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Steph van Hoffe (Key: 4UL4ZDDG6S)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.je-dag-in-beeld.caregiver
      vars:
        APP_ID: com.je-dag-in-beeld.caregiver
        BUNDLE_ID: com.je-dag-in-beeld.caregiver
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..
      - name: Flutter build ipa
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com  # Replace with your email
        notify:
          success: true
          failure: true
