workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - jedaginbeeld-release-profile
        certificates:
          - je-dag-in-beeld-distribution
      vars:
        APP_ID: com.je-dag-in-beeld.caregiver
        BUNDLE_ID: com.je-dag-in-beeld.caregiver
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..
      - name: Set up code signing
        script: |
          echo "Setting up code signing..."
          # List available certificates
          security find-identity -v -p codesigning
          # List provisioning profiles
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "No provisioning profiles directory found"
          # Get provisioning profile UUID
          PROVISIONING_PROFILE=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision | head -1)
          if [ -f "$PROVISIONING_PROFILE" ]; then
            echo "Found provisioning profile: $PROVISIONING_PROFILE"
            # Extract UUID from provisioning profile
            UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(security cms -D -i "$PROVISIONING_PROFILE" 2>/dev/null) 2>/dev/null)
            echo "Provisioning profile UUID: $UUID"
          else
            echo "⚠️ No provisioning profile found"
            UUID=""
          fi
          # Configure Xcode project for manual signing with App Store profile
          cd ios
          python3 << PYTHON_SCRIPT
          import re
          
          with open('Runner.xcodeproj/project.pbxproj', 'r') as f:
              content = f.read()
          
          # Find Release configuration (97C147071CF9000F007C117D)
          release_pattern = r'(97C147071CF9000F007C117D /\* Release \*/ = \{[^}]*buildSettings = \{)([^}]*)(\};)'
          
          def update_release_config(match):
              header = match.group(1)
              settings = match.group(2)
              footer = match.group(3)
              
              # Set CODE_SIGN_STYLE to Manual for App Store builds
              if re.search(r'CODE_SIGN_STYLE\s*=', settings):
                  settings = re.sub(r'CODE_SIGN_STYLE\s*=\s*[^;]+;', 'CODE_SIGN_STYLE = Manual;', settings)
              else:
                  settings = settings.rstrip() + '\n\t\t\t\tCODE_SIGN_STYLE = Manual;'
              
              # Set DEVELOPMENT_TEAM
              if re.search(r'DEVELOPMENT_TEAM\s*=', settings):
                  settings = re.sub(r'DEVELOPMENT_TEAM\s*=\s*[^;]+;', 'DEVELOPMENT_TEAM = 2633XR9X9L;', settings)
              else:
                  settings = settings.rstrip() + '\n\t\t\t\tDEVELOPMENT_TEAM = 2633XR9X9L;'
              
              # Set CODE_SIGN_IDENTITY to Apple Distribution
              if re.search(r'CODE_SIGN_IDENTITY\[sdk=iphoneos\*\]', settings):
                  settings = re.sub(r'"CODE_SIGN_IDENTITY\[sdk=iphoneos\*\]"\s*=\s*[^;]+;', '"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "Apple Distribution";', settings)
              else:
                  settings = settings.rstrip() + '\n\t\t\t\t"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "Apple Distribution";'
              
              # Set provisioning profile UUID if available
              uuid = "${UUID}"
              if uuid and uuid.strip():
                  if re.search(r'PROVISIONING_PROFILE_SPECIFIER\s*=', settings):
                      settings = re.sub(r'PROVISIONING_PROFILE_SPECIFIER\s*=\s*[^;]+;', f'PROVISIONING_PROFILE_SPECIFIER = {uuid};', settings)
                  else:
                      settings = settings.rstrip() + f'\n\t\t\t\tPROVISIONING_PROFILE_SPECIFIER = {uuid};'
              
              return header + settings + footer
          
          new_content = re.sub(release_pattern, update_release_config, content, flags=re.DOTALL)
          
          with open('Runner.xcodeproj/project.pbxproj', 'w') as f:
              f.write(new_content)
          
          print("✅ Configured Release for manual signing:")
          print("   - CODE_SIGN_STYLE = Manual")
          print("   - DEVELOPMENT_TEAM = 2633XR9X9L")
          print("   - CODE_SIGN_IDENTITY = Apple Distribution")
          if uuid and uuid.strip():
              print(f"   - PROVISIONING_PROFILE_SPECIFIER = {uuid}")
          PYTHON_SCRIPT
          cd ..
      - name: Flutter build ipa
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - syedasadullahkazmik@gmail.com  # Replace with your email
        notify:
          success: true
          failure: true
