// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOLnuJ736V3NU1VA1UId9K_0gg0JG1o54',
    appId: '1:929615381650:web:2b8dd8de8bbf1689be124b',
    messagingSenderId: '929615381650',
    projectId: 'caregiver-cba18',
    authDomain: 'caregiver-cba18.firebaseapp.com',
    storageBucket: 'caregiver-cba18.firebasestorage.app',
    measurementId: 'G-CJZ0BQKF3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAimfqIo6F8afMLQu4jkwKkyijxL6EEhrA',
    appId: '1:929615381650:android:049fef3cfaec642bbe124b',
    messagingSenderId: '929615381650',
    projectId: 'caregiver-cba18',
    storageBucket: 'caregiver-cba18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEkOQycup-JESgrmOqiVwJadjzwI2nbXo',
    appId: '1:929615381650:ios:e814e977cbca7ee0be124b',
    messagingSenderId: '929615381650',
    projectId: 'caregiver-cba18',
    storageBucket: 'caregiver-cba18.firebasestorage.app',
    iosBundleId: 'com.example.caregiver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEkOQycup-JESgrmOqiVwJadjzwI2nbXo',
    appId: '1:929615381650:ios:e814e977cbca7ee0be124b',
    messagingSenderId: '929615381650',
    projectId: 'caregiver-cba18',
    storageBucket: 'caregiver-cba18.firebasestorage.app',
    iosBundleId: 'com.example.caregiver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOLnuJ736V3NU1VA1UId9K_0gg0JG1o54',
    appId: '1:929615381650:web:277478030da6f986be124b',
    messagingSenderId: '929615381650',
    projectId: 'caregiver-cba18',
    authDomain: 'caregiver-cba18.firebaseapp.com',
    storageBucket: 'caregiver-cba18.firebasestorage.app',
    measurementId: 'G-RXV7C7NE4N',
  );
}
