// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // TODO: Get Web app configuration from Firebase Console
    // Firebase Console → Project Settings → Your apps → Web app
    // If Web app is not registered, register it first, then update these values
    apiKey: 'PLACEHOLDER_WEB_API_KEY', // ← Get from Firebase Console
    appId: 'PLACEHOLDER_WEB_APP_ID', // ← Get from Firebase Console (format: 1:PROJECT_NUMBER:web:APP_ID)
    messagingSenderId: '47836047261',
    projectId: 'je-dag-in-beeld',
    authDomain: 'je-dag-in-beeld.firebaseapp.com',
    storageBucket: 'je-dag-in-beeld.firebasestorage.app',
    measurementId: 'PLACEHOLDER_MEASUREMENT_ID', // ← Get from Firebase Console (format: G-XXXXXXXXXX)
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXIQ3GVR7Z9pIHNU-C-WWcXwP6ocKjo2s',
    appId: '1:47836047261:android:3b22d44972284e8baaf174',
    messagingSenderId: '47836047261',
    projectId: 'je-dag-in-beeld',
    storageBucket: 'je-dag-in-beeld.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi7Xo8su6v2VSvRUmXxc8GVMLdARajbTQ',
    appId: '1:47836047261:ios:f4c560c38e6c8ec6aaf174',
    messagingSenderId: '47836047261',
    projectId: 'je-dag-in-beeld',
    storageBucket: 'je-dag-in-beeld.firebasestorage.app',
    iosBundleId: 'com.je-dag-in-beeld.caregiver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi7Xo8su6v2VSvRUmXxc8GVMLdARajbTQ',
    appId: '1:47836047261:ios:f4c560c38e6c8ec6aaf174',
    messagingSenderId: '47836047261',
    projectId: 'je-dag-in-beeld',
    storageBucket: 'je-dag-in-beeld.firebasestorage.app',
    iosBundleId: 'com.je-dag-in-beeld.caregiver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    // TODO: Get Windows app configuration from Firebase Console
    // Windows uses Web app configuration. Register Web app if not done, then use same values here
    // Firebase Console → Project Settings → Your apps → Web app
    apiKey: 'PLACEHOLDER_WEB_API_KEY', // ← Get from Firebase Console (same as Web)
    appId: 'PLACEHOLDER_WEB_APP_ID', // ← Get from Firebase Console (same as Web or separate Windows app)
    messagingSenderId: '47836047261',
    projectId: 'je-dag-in-beeld',
    authDomain: 'je-dag-in-beeld.firebaseapp.com',
    storageBucket: 'je-dag-in-beeld.firebasestorage.app',
    measurementId: 'PLACEHOLDER_MEASUREMENT_ID', // ← Get from Firebase Console (same as Web)
  );
}
